alliance-genome/agr_curation_schema

model/schema/allianceModel.yaml
model/schema/geneInteraction.yaml

First submission of geneInteraction.yaml to agr-curation-schema

First submission of geneInteraction.yaml to agr-curation-schema

---

model/schema/allele.yaml
model/schema/variantConsequence.yaml
model/schema/variation.yaml

Migration of some changes from the old repo not yet brought over.  Tidying up of allele and variant schemas.

Allele variant updates

---

model/schema/core.yaml

Make taxon required for BiologicalEntity class and symbol
required for Gene class

SCRUM-248 Update to required fields

---

model/schema/allele.yaml
model/schema/core.yaml

A few minor updates based on alleles working group minutes

Allele updates

---

model/schema/phenotypeAndDiseaseAnnotation.yaml

Also, changed evidence_code slot name to evidence_codes

Made "ECOTerm" range for "evidence_code" slot

---

model/schema/phenotypeAndDiseaseAnnotation.yaml

Changed generic OntologyTerm ranges to more specific terms now in the LinkML model

Update ExperimentalCondition slot_usage ranges

---

model/schema/allianceModel.yaml
model/schema/controlledVocabulary.yaml
model/schema/core.yaml
model/schema/ontologyTerm.yaml

Added file with the controlled vocabulary LinkML model
@chris-grove would you please review and let me know if it needs any corrections

added controlled vocabulary yaml

---

model/schema/controlledVocabulary.yaml
model/schema/core.yaml
model/schema/ontologyTerm.yaml

PR without auto-generated files

SCRUM-879 vocabulary changes

---

model/schema/core.yaml
test/data/disease_agm_test.json
test/data/disease_allele_test.json
test/data/disease_gene_test.json

NB - I'm leaving EntityStatement in place now so that I can coordinate the replacement of it with the expression working group, but I wanted to get the new Note in place ASAP.

SCRUM-1185: Add "Note" object.

---

jsonld-context/allianceModel.context.jsonld
jsonschema/allianceModel.schema.json
model/schema/allianceModel.yaml
model/schema/core.yaml
model/schema/expression.yaml
model/schema/reagent.yaml
python/affectedGenomicModel.py
python/allele.py
python/allianceModel.py
python/antibody.py
python/controlledVocabulary.py
python/core.py
python/expression.py
python/geneInteraction.py
python/image.py
python/informationContentEntity.py
python/ingest.py
python/ontologyTerm.py
python/orthology.py
python/person.py
python/phenotypeAndDiseaseAnnotation.py
python/reference.py
python/resource.py
python/test.py
python/variantConsequence.py
python/variation.py

rule example is [here](https://github.com/alliance-genome/agr_curation_schema/pull/89/files#diff-3ad08fceb1ae6b213a6928861837d185e21feb175747cf56cd1fe129116340ba)

Add rules examples

---

model/schema/allele.yaml

Removed redundant affected_genes slot

Allele association updates

---

model/schema/core.yaml

Add note_type permissible values to Note class description

Add note_type permissible values to Note

---

jsonld-context/allianceModel.context.jsonld
jsonschema/allianceModel.schema.json
python/affectedGenomicModel.py
python/allele.py
python/allianceModel.py
python/controlledVocabulary.py
python/core.py
python/expression.py
python/geneInteraction.py
python/informationContentEntity.py
python/ingest.py
python/ontologyTerm.py
python/orthology.py
python/person.py
python/phenotypeAndDiseaseAnnotation.py
python/reagent.py
python/reference.py
python/resource.py
python/test.py
python/variantConsequence.py
python/variation.py

I took a look at the PRs that have gone in since the last tag and I don't think tagging back in time is necessary - no breaking changes have gone since the last tag.

regenerate artifacts

---

model/schema/core.yaml
model/schema/informationContentEntity.yaml
model/schema/reference.yaml
model/schema/resource.yaml

New PR into the correct repo! For https://agr-jira.atlassian.net/browse/SCRUM-1142

update reference to conform to literature database

---

model/schema/ontologyTerm.yaml

Both derived from the XAO ontology
Anatomy term class will be 'XBATerm'
Life stage term class will be 'XBSTerm'

Adding Xenopus anatomy and stage ontology term classes

---

model/schema/bulkload.yaml
model/schema/core.yaml
model/schema/curationReport.yaml

SCRUM-1509 CurationReport model for BIRT reports

---

model/schema/agent.yaml

Slot for storing JSON Blob of curation DB UI settings

SCRUM-1080 Add user_settings slot to LoggedInPerson

---

model/schema/-
model/schema/biologicalEntitySet.yaml
model/schema/gene.yaml
model/schema/phenotypeAndDiseaseAnnotation.yaml

Hi guys, 
I tried to add some slots to  GeneCluster,  GeneClass and  Operon, so that they will be able to harbour all WB data.
It is more of a draft than proper code, because I don't know exactly how to code it correctly, but I hope to learn :-)

biologicalEntitySet updated with draft WB fields

---

test/data/disease_agm_test.json
test/data/disease_allele_test.json
test/data/wb_disease_test.json

I cannot get make commands to run locally, so can someone confirm successful make with these changes?

Add-test-data-for-asserted-inferred-gene-allele-and-condition_free_text

---

model/schema/agent.yaml
model/schema/core.yaml
model/schema/curationReport.yaml
model/schema/ontologyTerm.yaml
test/data/agm_test.json
test/data/sqtr_test.json

Various changes to bring LinkML schema in line with A-Team curation DB code

SCRUM-1925

---

model/schema/bulkload.yaml

Add slot for recording the time that a file was last loaded.

SCRUM-2000 Add date_last_loaded slot to BulkLoadFile

---

util/validate_agr_schema.py

I find it helpful in my pipelines to have validation script raise an error if validation fails, so suggesting it here in case others might find it helpful too (or at least innocuous).

raise error if validation fails

---

.github/workflows/check-pull-request.yaml
generated/jsonschema/allianceModel.schema.json
model/schema/affectedGenomicModel.yaml
model/schema/core.yaml
model/schema/phenotypeAndDiseaseAnnotation.yaml
test/data/agm_test.json
test/data/allele_association_ingest_test.json
test/data/allele_slot_annotation_ingest_test.json
test/data/allele_test.json
test/data/gene_test.json
test/data/sqtr_test.json
test/data/variant_test.json

Add data_provider slot to BiologicalEntity class in order to facilitate loading of non-canonical species by MODs

SCRUM-2719 Add data provider to BiologicalEntity

---

generated/jsonschema/allianceModel.schema.json
model/schema/allele.yaml
model/schema/alleleDTO.yaml
model/schema/core.yaml
test/data/agm_test.json
test/data/allele_association_ingest_test.json
test/data/allele_slot_annotation_ingest_test.json
test/data/allele_test.json
test/data/disease_agm_test.json
test/data/disease_allele_test.json
test/data/disease_gene_test.json
test/data/fb_disease_test.json
test/data/gene_test.json
test/data/ontology_closure_test.json
test/data/sgd_disease_test.json
test/data/sqtr_test.json
test/data/variant_allele_association_test.json
test/data/variant_test.json
test/data/wb_disease_test.json

* Update LinkML schema version in agr_curation_schema test files
* Remove molecular mutation slots from Allele and AlleleDTO classes and overall model
** Remove 'allele_molecular_mutation_dtos' slot definition and reference in AlleleDTO class
** Remove 'allele_molecular_mutations' slot definition and reference in Allele class
** Remove 'allele_notes' and 'allele_note_dtos' slots from Allele and AlleleDTO classes
** Remove AlleleNoteSlotAnnotation and AlleleNoteSlotAnnotationDTO classes
** Add 'related_notes' slot to Allele class and 'note_dtos' slot to AlleleDTO class
** Remove MolecularMutationSlotAnnotation classes AlleleMolecularMutationSlotAnnotationDTO and AlleleMolecularMutationSlotAnnotation
** Remove 'molecular_mutations' and 'molecular_mutation_names' slot definitions and …

Model updates may 16 2023

---

generated/jsonschema/allianceModel.schema.json
model/schema/ontologyTerm.yaml

@chris-grove I presume all these new terms inherit directly from OntologyTerm

Add new ontology terms

---

generated/jsonschema/allianceModel.schema.json
model/schema/allele.yaml
model/schema/core.yaml
model/schema/phenotypeAndDiseaseAnnotation.yaml

- Removed redundant evidence slots
- Added CV titles to notes

Clean up association classes evidence and predicates

---

generated/jsonschema/allianceModel.schema.json
model/schema/allele.yaml
model/schema/alleleDTO.yaml
model/schema/reagent.yaml

Several updates to the Construct class and related classes

Construct updates may 25, 2023

---

generated/jsonschema/allianceModel.schema.json
model/schema/allele.yaml
model/schema/biologicalEntitySet.yaml
model/schema/core.yaml
model/schema/expression.yaml
model/schema/geneInteraction.yaml
model/schema/ontologyTerm.yaml
model/schema/phenotypeAndDiseaseAnnotation.yaml
model/schema/reagent.yaml
model/schema/variantDTO.yaml
test/data/allele_association_ingest_test.json
test/data/ontology_closure_test.json
test/data/variant_allele_association_test.json
test/data/variant_association_ingest_test.json

This is what I was thinking along the lines of for Association changes

Association update proposal

---

generated/jsonschema/allianceModel.schema.json
model/schema/core.yaml
model/schema/expression.yaml
model/schema/image.yaml
model/schema/modCorpusAssociation.yaml
model/schema/ontologyTerm.yaml
model/schema/reagent.yaml
model/schema/reference.yaml
model/schema/resource.yaml

As discussed at the DQM/Modelling meeting on 21st Nov

Curie refactor

---

generated/jsonschema/allianceModel.schema.json
model/schema/allele.yaml
model/schema/core.yaml

Need to require name and taxon for Chromosome and not require evidence_curies for AlleleGeneAssociationDTO

Fix requirements for chromosome etc

---

Makefile
generated/jsonschema/allianceModel.schema.json
model/schema/allele.yaml
model/schema/ingest.yaml
test/data/sqtr_association_ingest_test.json
test/data/sqtr_test.json

Add name, synonyms, and secondary IDs to SQTR class

Sqtr modifications

---

generated/jsonschema/allianceModel.schema.json
model/schema/core.yaml
test/data/assembly_component_test.json

Switch display_name to name to bring in line with other GenomicEntity classes

Assembly component tweak

---

generated/jsonschema/allianceModel.schema.json
model/schema/variantDTO.yaml
model/schema/variation.yaml
test/data/variant_association_ingest_test.json

Remove redundant field and update range of dna_mutation_type and gene_localization_type to SOTerm

Tweaks to variant model

---

Makefile
generated/jsonschema/allianceModel.schema.json
model/schema/affectedGenomicModel.yaml
model/schema/allele.yaml
model/schema/core.yaml
model/schema/ingest.yaml
model/schema/reagent.yaml
test/data/agm_association_ingest_test.json
test/data/cassette_test.json
test/data/construct_test.json
test/data/str_association_ingest_test.json
test/data/str_test.json

Add Use to Cassette, Cassette STR Association
