model/schema/core.yaml, model/schema/geneInteraction.yaml, model/schema/ontologyTerm.yaml, model/schema/orthology.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml
For `core.yaml`:
- Generic "Entity" created in core since it was referenced as parent of "OntologyTerm".
For `ontologyTerm.yaml`:
- Made `xrefs` slot a child of `cross_references` slot, imported from `crossReference.yaml`
For `geneInteraction.yaml`:
- Made "aggregation_database_enum" for the "aggregation_database" slot to get things working - not sure if there's a better way.
- Fixed typo in reference to `related_to` predicate.
For `orthology.yaml`:
- Removed redundant creation of `predicate` slot.
For `phenotypeAndDiseaseAnnotation.yaml`:
- Typos
=> minimal changes required to get "make install all" working

model/schema/antibody.yaml
Possibly a quirk of the OO-generator code, but I ran into errors because prefixes were left out on just this file.
=> Added prefix stanza to the antibody schema yaml

model/schema/phenotypeAndDiseaseAnnotation.yaml
- Removal of unnecessary 'Disease' class; replaced by 'DOTerm' class
- Create 'ConditionRelation' class for to create pairings of a single experimental condition relation (e.g. has_condition) with a set of 1 or more ExperimentalCondition objects; This most closely resembles the existing agr_schemas JSON model and allows 'direct' connection from annotations (like DiseaseAnnotation) to ExperimentalCondition objects
- Addition of supporting slots 'condition_relations', 'condition_relation_type' and 'conditions'
- Removal of now unnecessary 'PhenotypeAnnotationExperimentalConditionAssociation' and 'DiseaseAnnotationExperimentalConditionAssociation' classes
Running of 'make all' built all artifacts without any interrupting errors.
=> Condition relation and supporting changes

model/schema/core.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml
I think the inlining feature goes a long way towards simplifying the DQM submissions, by generating nested JSON schemas.   For example, the conditionRelations are nested within the disease annotation classes:
```
"AlleleDiseaseAnnotation": {
"additionalProperties": false,
"description": "An annotation asserting an association between an allele and a disease supported by evidence.",
"properties": {
"annotation_reference": {
"description": "The reference in which the disease association was asserted/reported.",
"type": "string"
},
"annotation_type": {
"$ref": "#/$defs/AnnotationTypeEnum",
"description": "The type of annotation classified according to curation method: manually curated, high-throughput, computational"
},
"condition_relations": {
"items": {
"$ref": "#/$defs/ConditionRelation" …
```
=> Initial use of inlining to create nested JSON schema

model/schema/core.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml
- Added PaperHandle class and paper_handle and handle slots
- Declared 'reference' (single-valued) slot in core (distinct from 'references' slot)
- Changed 'annotation_reference' to just 'reference'
- Declared 'annotation_type' and 'genetic_sex' not required in DiseaseAnnotation class
- Fixed model syntax error
=> PaperHandle class, paper_handle slot, other edits

model/schema/core.yaml
Identifier flag is incompatible with non-required field
=> Remove identifier flag

model/schema/phenotypeAndDiseaseAnnotation.yaml
Given the change from curie to unique_id on the DiseaseAnnotation class, I assume that this should also be done for the ConditionRelation and ExperimentalCondition classes which also a compound key (at the moment) rather than a curie.  This would avoid DQMs having to generate curies for these entities.
=> SCRUM-1037 More curie to unique_id changes

model/schema/ontologyTerm.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml
The conditionChemical field of the ExperimentalCondition class
needs to be able to contain either a CHEBITerm or a Molecule.
Proposed solution is to create an abstract ChemicalTerm class,
which is an OntologyTerm.  Both CHEBITerm and Molecule will then
be ChemicalTerm subclasses.
=> Proposed solution to conditionChemical issue

model/schema/antibody.yaml
These suggested changes were necessitated by the implementation of the new "Note" class, which is intended to replace the "EntityStatement" class.
Even though they are no longer referenced by anything, I left the `antibody_note_type_set` enum there for future reference. I suspect these will need to become ControlledVocabularyTerm objects so that the proper Note types can be created.
=> Add "related_notes" slot to "Antibody" class and delete the "AntibodyStatement" class.

test/data/fb_disease_test.json
@gildossantos  I'm going to suggest removing the 'inferred_gene' entry as that is intended to be only derived automatically (by yet-to-be-instantiated "roll-up" rules) and not submitted.
=> Remove 'inferred_gene' entry

model/schema/phenotypeAndDiseaseAnnotation.yaml, test/data/invalid/allele_invalid.json, test/data/invalid/disease_allele_invalid.json
Added 'asserted_gene' and 'asserted_allele' slots for disease and phenotype annotations for when a curator wants to assert gene or allele associations in addition to a subject declaration, for example when an allele affects multiple genes but the authors demonstrate that it is one gene in particular that is responsible for the disease or phenotype.
=> Add asserted_gene and asserted_allele slots

.github/workflows/check-pull-request.yaml, Makefile, jsonschema/allianceModel.schema.json, model/schema/allele.yaml, model/schema/biologicalEntitySet.yaml, model/schema/core.yaml, model/schema/expression.yaml, model/schema/ontologyTerm.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml, test/data/agm_test.json, test/data/allele_test.json, test/data/disease_agm_test.json, test/data/disease_allele_test.json, test/data/disease_gene_test.json, test/data/fb_disease_test.json, test/data/gene_test.json, test/data/sgd_disease_test.json, test/data/sqtr_test.json, test/data/variant_test.json, test/data/wb_disease_test.json
Running 'make all' seems to work well. I get an error when running 'make test':
```
$ make test
rm -rf target/*
rm -rf jsonschema/*
mkdir -p target/jsonschema
poetry run gen-json-schema  --closed -t ingest model/schema/allianceModel.yaml > target/jsonschema/allianceModel.schema.json
WARNING:JsonSchemaGenerator:Unrecognized prefix: MSigDB
cp -pr target/jsonschema .
poetry run jsonschema -i test/data/allele_test.json jsonschema/allianceModel.schema.json
The currently activated Python version 3.7.4 is not supported by the project (^3.8).
Trying to find and use a compatible version. 
Using python3.8 (3.8.3)
Failed to parse 'jsonschema/allianceModel.schema.json': Expecting value: line 1 column 1 (char 0)
make: *** [validate-allele_test] Error 1
```
It seems like it was OK using Python 3.8 but …
=> Added curie to DiseaseAnnotation and test examples

model/schema/core.yaml
Two classes representing AGR identifier and a consecutive range of identifiers. These will be used in MaTI and future MaTI API consumers (A and Blue teams)
=> SCRUM-1855: represent a range of identifiers

jsonschema/allianceModel.schema.json, model/schema/ingest.yaml, test/data/agm_test.json, test/data/allele_association_ingest_test.json, test/data/allele_slot_annotation_ingest_test.json, test/data/allele_test.json, test/data/disease_agm_test.json, test/data/disease_allele_test.json, test/data/disease_gene_test.json, test/data/fb_disease_test.json, test/data/gene_test.json, test/data/invalid/allele_invalid.json, test/data/invalid/disease_allele_invalid.json, test/data/invalid/missing_version.json, test/data/invalid/variant_invalid.json, test/data/ontology_closure_test.json, test/data/sgd_disease_test.json, test/data/sqtr_test.json, test/data/variant_allele_association_test.json, test/data/variant_test.json, test/data/wb_disease_test.json
This will allow us to prevent reloading previously submitted files that were submitted to LinkML schema versions incompatible with current Java code.
=> SCRUM-2119 Require DQMs to submit LinkML schema version with ingest files

model/schema/allele.yaml, test/data/allele_slot_annotation_ingest_test.json
@sierra-moxon Can we do this switch for allele_id in the AlleleSlotAnnotation?  We would want to implement this field as an Allele object in our Java entity classes.
=> Replace allele_id with single_allele

model/schema/core.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml, test/data/disease_agm_test.json, test/data/disease_allele_test.json, test/data/disease_gene_test.json, test/data/fb_disease_test.json, test/data/sgd_disease_test.json, test/data/wb_disease_test.json
-replaced 'alliance_curie' in DiseaseAnnotation class with 'disease_annotation_curie' slot
- added slot definition for 'disease_annotation_curie'
- alphabetized slot definitions in phenotypeAndDiseaseAnnotation.yaml
- removed comment TO DO item for GOTerm
=> Add 'disease_annotation_curie' to DiseaseAnnotation class

model/schema/allele.yaml, test/data/allele_test.json
For the Allele class, 'name' should not be required but 'symbol' should be
=> Change required properties for Allele

jsonschema/allianceModel.schema.json, model/schema/affectedGenomicModel.yaml, model/schema/allele.yaml, model/schema/core.yaml, model/schema/gene.yaml, model/schema/image.yaml, model/schema/ingest.yaml, model/schema/ontologyTerm.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml, model/schema/reference.yaml, model/schema/variation.yaml, test/data/agm_test.json, test/data/allele_association_ingest_test.json, test/data/allele_slot_annotation_ingest_test.json, test/data/allele_test.json, test/data/disease_agm_test.json, test/data/disease_allele_test.json, test/data/disease_gene_test.json, test/data/fb_disease_test.json, test/data/gene_test.json, test/data/invalid/allele_invalid.json, test/data/invalid/disease_allele_invalid.json, test/data/invalid/missing_version.json, test/data/sgd_disease_test.json, test/data/variant_allele_association_test.json, test/data/wb_disease_test.json
As a result of a discussion within the A-Team, we believe the best way forward or the LinkML model is to separate ingest modelling from database / Java code modelling.  This is an initial proposed remodel for the classes currently ingested by the A-Team's curation database.  This accurately represents both our ingest DTO classes and our entity classes (used to generate the database schema via Hibernate).  It allows for fields to be required in the database but not in the ingest files, and allows both forward- and back-references to be explicitly described in the LinkML model.  
@oblodgett, @chris-grove  - Any initial feedback before taking this to the wider modelling group?
=> Proposal for separation of ingest and database concerns in LinkML model

model/schema/agent.yaml, model/schema/allele.yaml, model/schema/controlledVocabulary.yaml, model/schema/core.yaml
- Add affiliated_alliance_member slot to Person class
- Make 'allele_notes' slot multivalued
- removed 'private_comment' slot
- Make allele_germline_transmission_status (and dto slot) single-valued
- Set domain of 'text_synonyms' to VocabularyTerm
=> Miscellaneous updates for A-Team Dec 2022

model/schema/allele.yaml, model/schema/alleleDTO.yaml, model/schema/allele_dto.yaml, model/schema/allianceModel.yaml, test/data/allele_association_ingest_test.json, test/data/variant_allele_association_test.json
- used allele.yaml as a pilot case
- Moved all DTO classes and DTO-specific slots to allele_dto.yaml
- Alphabetized all class and slot definitions within their respective sections
=> Model reorganization effort attempt 1

model/schema/affectedGenomicModel.yaml
'subtype' is already a required field, but the corresponding DTO field had not been set as being required
=> Make subtype_name required for AGM submissions

model/schema/gene.yaml
I think that these changes to the DTOs mirror specs for the corresponding non-DTO objects.
1. Not all fly genes have a systematic name - about half of D. melanogaster genes have not been mapped to the genome.
2. Not all fly genes have a full name. Genes only known by a systematic name do not have full names. In another scenario, the gene symbol and full_name are identical.
=> full_name and systematic_name DTOs should be optional for genes

test/data/variant_test.json
There was a Variant in the variant test file that was missing a data provider, causing the tests to fail. This fixes that.
=> Add-data-provider-to-Variant-in-test-file

generated/jsonschema/allianceModel.schema.json, model/schema/controlledVocabulary.yaml, model/schema/core.yaml, model/schema/ontologyTerm.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml, test/data/wb_disease_test.json
- Added several new ontology term classes
- Added 'mod_internal_id' slot definition; slot added to DiseaseAnnotation class
- Added 'synonyms' slot to VocabularyTerm class; updated description of 'synonyms' slot in core.yaml
- Changed 'disease_genetic_modifier' slot to 'disease_genetic_modifiers' and made multivalued
=> A-Team updates: new phenotypes, multiple genetic modifiers, etc.

generated/jsonschema/allianceModel.schema.json, model/schema/affectedGenomicModel.yaml, model/schema/allele.yaml, model/schema/alleleDTO.yaml, model/schema/core.yaml, model/schema/gene.yaml, test/data/agm_test.json, test/data/allele_test.json, test/data/gene_test.json, test/data/sqtr_test.json
In the current model the `GenomicEntity` class has a `secondary_identifiers` slot, which is multivalued and has a range of `string.`  However, the `Allele` class inherits that slot but also has `allele_secondary_ids` with a range of `AlleleSecondaryIdSlotAnnotation`.  We don't want `Allele` to have both slots, and presumably we want to use the SlotAnnotation paradigm for secondary IDs elsewhere.
In this PR I have removed `secondary_identifiers` from `GenomicEntity` and implemented the SlotAnnotation paradigm for genes and AGMs - we may wish to also do so for other classes that inherit from GenomicEntity or we may wish to stick with the simpler list of strings for those, or not even have secondary IDs at all for some classes.
=> Secondary IDs update

model/schema/reagent.yaml
@draciti @gildossantos 
I think you (or someone in the Expression working group) had created the original Reagent class definition, including a requirement on taxon and curie. This pull request is to remove the requirement for taxon and curie, since we have Construct as a subclass of Reagent and, at least for WormBase, we cannot require specification of a single taxon (or any taxon in some cases). Also, it is unclear to me if we know, at this point, that all Reagent records will necessarily have a curie. If I can confirm that all Reagents (including instances of Construct, Antibody, DNAClone, and RNAClone) will have a curie coming from the MOD, then we can keep that constraint. 
Let me know what you think.
=> Relax curie and taxon requirements for Reagent class

Makefile, generated/jsonschema/allianceModel.schema.json, model/schema/affectedGenomicModel.yaml, model/schema/allele.yaml, model/schema/core.yaml, model/schema/ingest.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml, model/schema/reagent.yaml, test/data/allele_association_ingest_test.json, test/data/construct_test.json
There are currently a couple of slots that may need to change (`generated_by_identifier` and `manufacture_by_identifier`).  The non-DTO versions of these slots have a range of `Agent`, but there is no common identifying field for `Agent`: the `Person` class has `unique_id`, `Laboratory` has `curie`, `Company` and `Organization` don't have any identifier.  We will need to resolve this in the modelling of the Agent class and subclasses and then update these two field names to be something more descriptive.
=> SCRUM-3230 Construct ingest classes

generated/jsonschema/allianceModel.schema.json, model/schema/reagent.yaml, test/data/antibody_test.json, test/data/construct_test.json
@chris-grove Constructs (and presumably other reagents) are going to be a submitted datatype.  As such, we will need data_provider for cleanup purposes.
=> Add data provider to Reagent class

generated/jsonschema/allianceModel.schema.json, model/schema/ingest.yaml, model/schema/reagent.yaml, test/data/construct_test.json
The Construct class needs synonyms, secondary IDs and cross references. These have now been added to the Reagent and ReagentDTO superclasses to accommodate the Construct and Antibody classes (FlyBase currently submits these properties for Construct submissions to the FMS).
=> Add synonyms, 2ndary IDs, XREFs to Reagent

generated/jsonschema/allianceModel.schema.json, model/schema/gene.yaml
Updated formatting of the `GeneChangeEventSlotAnnotation` description in an attempt to fix the display issues in the LinkML model browser.
=> reformat GeneChangeEventSlotAnnotation description

generated/jsonschema/allianceModel.schema.json, model/schema/gene.yaml
Simple changes to bring LinkML model in line with agr_schemas model.
1. Add gene_synopsis slot (a simple string).
2. Make gene_type/gene_type_curie (aka soTermId, gene biotype) a required slot for Gene/GeneDTO classes
I want to handle gene genomic locations in a separate PR.
=> align with FMS submission: add gene_synopsis, make gene_type required

generated/jsonschema/allianceModel.schema.json, model/schema/allele.yaml, model/schema/biologicalEntitySet.yaml, model/schema/core.yaml, model/schema/expression.yaml, model/schema/gene.yaml, model/schema/geneInteraction.yaml, model/schema/ontologyTerm.yaml, model/schema/orthology.yaml, model/schema/phenotypeAndDiseaseAnnotation.yaml, model/schema/reagent.yaml, model/schema/variantConsequence.yaml, model/schema/variation.yaml, test/data/ontology_closure_test.json
Alternative version of association slot refactor using domain class prefix to differentiate, as discussed in sprint planning.  As per Sierra's suggestion, I've used "attributes" where possible to define slots inline in the classes if reuse of the slot is not intended.
=> Refactor association slots using domain prefix

generated/jsonschema/allianceModel.schema.json, model/schema/homology.yaml
After discussing with @christabone who has discussed with DIOPT:
We will remove the requirement of Paralogous gene pairs to have a length, similarity, or identity scores.
=> Remove requirement of Paralogy identity, similarity, and length

generated/jsonschema/allianceModel.schema.json, model/schema/variantConsequence.yaml, model/schema/variation.yaml
Moves away from the "association of an association" model to just having a single class for VEP consequences that is attached to a CuratedVariantGenomicLocationAssociation (multivalued).
The gene-level consequence is simply the most severe transcript-level consequence for a variant amongst all the transcripts associated with a gene, so this can simply be indicated by a boolean rather than having separate gene- and transcript-level consequence classes.
Position slots prefixed with 'calculated_' to clearly indicate that these coordinates are determined by the VEP based on input files as opposed to source/curated values.
=> SCRUM-4441 Rewrite LinkML model for VEPGENE and VEPTRANSCRIPT loader data types

generated/jsonschema/allianceModel.schema.json, model/schema/expression.yaml
Simple addition of a 'cross_reference' slot to ExpressionExperiment class
=> Add cross reference to ExpressionExperiment

.github/workflows/build-deploy-documentation.yaml, .github/workflows/check-pull-request.yaml, .github/workflows/regenerate_artifacts.yaml
These permission definitions are now required in all GH actions workflow files to enable workflows to write to their repository where needed (and only where needed), as the default permissions have been update to read-only access to the repository contents.
=> Added required content write permissions to handle new read-only default

model/schema/core.yaml
- Indicated uniqueness constrain on primary IDs for all BiologicalEntity (and DTO) records
- Indicated that SubmittedObject (and DTO) records should either be assigned a public primary_external_id or a private mod_internal_id
=> Update description of ID uniqueness constraint to BiologicalEntity

Makefile
WARNING:linkml.generators.jsonschemagen:No class in schema named ingest
cp -pr generated/target/jsonschema generated/
better warning message in more recent versions of linkml notified us that we need to update the casing of "Ingest" class in order to be recognized as a valid class in agr_curation_schema.
=> recognize casing of Ingest class

generated/jsonschema/allianceModel.schema.json, model/schema/phenotypeAndDiseaseAnnotation.yaml
Small fix; for some reason (probably from my original implementation) the date_created field was required (but shouldn't be) and the single_reference was not required (but should be). This should fix that.
=> Fix date created requirement for phenotype annotation
